# Generated by Django 5.2.2 on 2025-06-04 18:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concesionario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('surcursal', models.CharField(blank=True, max_length=100, null=True)),
                ('aspirante', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
